---
# Bring Stack Down
- hosts: servers
  become: true
  tasks:
    - service: name=nginx state=stopped

# Restart mysql
- hosts: servers
  become: true
  tasks:
    - service: name=mysql state=restarted

# Bring Stack up
- hosts: servers
  become: true
  tasks:
    - service: name=nginx state=restarted
